### ISSUE TITLE
Bug in filecontent detector: adds an empty filename as detection

### ISSUE THREAD

**Issue by aswinkarthik** [thoughtworks/talisman#158]
**Describe the bug**
On running talisman, when it detects passwords in filecontent, the actual file + an empty string is shown as a detection. This is due to the introdcution of channels.

**To Reproduce**
1. Create a `temp-file` using `echo "password: thisIsAPassword" > temp-file`
2. `git add temp-file`
3. `talisman --githook pre-commit`

**Expected behavior**
```
fileignoreconfig:
- filename: temp-file
  checksum: 2c7a2f21935098cfe63b8532f1f4495fcd3975bc43c4d37b9a78aa33b5f3c1d3
  ignore_detectors: []
scopeconfig: []
```

**Screenshots**
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/6232245/67570092-30d0a280-f74e-11e9-9173-5c1a8ece71c0.png">

If you notice, there is an entry with "".

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: master

## Cause:

This is due to how we do a select on channels in filecontent_detector.
