### ISSUE TITLE
Directions for using with pre-commit are incorrect

### ISSUE THREAD

**Issue by asottile** [thoughtworks/talisman#273]
It should suggest a yaml like this:

```yaml
-   repo: https://github.com/thoughtworks/talisman
    rev: ...
    hooks:
    -   id: talisman-commit   # or `-   id: talisman-push`
```

and pre-commit works on windows as well
