### ISSUE TITLE
Custom Severity level

### ISSUE THREAD

**Issue by umasad087** [thoughtworks/talisman#337]
### Discussed in https://github.com/thoughtworks/talisman/discussions/336

<div type='discussions-op-text'>

<sup>Originally posted by **umasad087** September 10, 2021</sup>
Hi Talisman Community,

I am trying to configure custom severity level for our gitlab repositories. I have set the severity levels in the talismanrc file but I am unable to confirm if the custom severity level have taken affect. When I try to commit changes it do not block my changes where as I am expected them to be blocked due to the severity levels set in talismanrc. Can someone please help me understand how it works and what can be done to test and troubleshoot the custom severity.

Thanks,
Umasad</div>

**Comment by tinamthomas** [comment]
Hi @umasad087 

Could you post your talismanrc configuration with the custom severity?

**Comment by umasad087** [comment]
Hi @tinamthomas 

Please see our talismanrc

custom_severities:
- detector: ShellHistory
  severity: medium
- detector: ASCFile
  severity: medium
- detector: KDBFile
  severity: medium
- detector: AgileKeyChainFile
  severity: medium
- detector: PubXML
  severity: medium
- detector: GitRobRC
  severity: medium
- detector: ShellRC
  severity: medium
- detector: CreditCardContent
  severity: medium
- detector: ShellProfile
  severity: medium
- detector: ShellAlias
  severity: medium
- detector: OmniAuth
  severity: medium
- detector: CarrierWaveRB
  severity: medium
- detector: SchemaRB
  severity: medium
- detector: PythonSettings
  severity: medium
- detector: PhpConfig
  severity: medium
- detector: PhpLocalSettings
  severity: medium
- detector: OmniAuth
  severity: medium
- detector: EnvFile
  severity: medium
- detector: BDumpFile
  severity: medium
- detector: BSQLFile
  severity: medium
- detector: PasswordFile
  severity: medium
- detector: BackupFile
  severity: medium
- detector: LogFile
  severity: medium
- detector: KWallet
  severity: medium
- detector: GNUCash
  severity: medium
- detector: PasswordPhrasePattern
  severity: medium
- detector: LargeFileSize
  severity: medium

**Comment by tinamthomas** [comment]
@umasad087 Thanks for uploading your talismanrc. 

To address your first problem about the commit not being blocked, regardless of setting the custom severities, when you try to commit (say for example a log file with some contents in it), the commit should be blocked.

<img width="1204" alt="talisman1" src="https://user-images.githubusercontent.com/42120196/133532858-5e81d057-e064-457a-bea8-8cf430c69102.png">

There are some reasons that could be the problem.

1. Did you install talisman as a pre-commit hook as described here: https://github.com/thoughtworks/talisman#installation-as-a-global-hook-template
2. Could you check in your talismanrc if you have any threshold set in your .talismanrc ? If the threshold is high and all the warnings are low or medium, that could be another reason the commit isn't blocking.

Once we've figured out why the commit isn't blocking for you, we can look at custom severity configurations.

**Comment by umasad087** [comment]
@tinamthomas thank you for your detailed response. 

Answer to your two questions are:
1. Yes, I did follow this method to install the talisman as a pre-commit. 
2. Currently, we have few entries for fileignoreconfig checksum but no threshold set.

**Comment by svishwanath-tw** [comment]
@umasad087 : please paste the YAML of `.talismanrc` in a code block
I ask this because sometimes invalid YAML is silently ignored.
Things like missing a blank line in the end. Using tabs and spaces interchangeably etc.

**Comment by umasad087** [comment]
`custom_severities:
  - detector: ShellHistory
    severity: medium
  - detector: ASCFile
    severity: medium
  - detector: KDBFile
    severity: medium
  - detector: AgileKeyChainFile
    severity: medium
  - detector: PubXML
    severity: medium
  - detector: GitRobRC
    severity: medium
  - detector: ShellRC
    severity: medium
  - detector: CreditCardContent
    severity: medium
  - detector: ShellProfile
    severity: medium
  - detector: ShellAlias
    severity: medium
  - detector: OmniAuth
    severity: medium
  - detector: CarrierWaveRB
    severity: medium
  - detector: SchemaRB
    severity: medium
  - detector: PythonSettings
    severity: medium
  - detector: PhpConfig
    severity: medium
  - detector: PhpLocalSettings
    severity: medium
  - detector: OmniAuth
    severity: medium
  - detector: EnvFile
    severity: medium
  - detector: BDumpFile
    severity: medium
  - detector: BSQLFile
    severity: medium
  - detector: PasswordFile
    severity: medium
  - detector: BackupFile
    severity: medium
  - detector: LogFile
    severity: medium
  - detector: KWallet
    severity: medium
  - detector: GNUCash
    severity: medium
  - detector: PasswordPhrasePattern
    severity: medium
  - detector: LargeFileSize
    severity: medium
fileignoreconfig:
- filename: .gitlab/certs/harbor.app.gdit-dsop.io.crt
  checksum: b8f9ca166189b507a45f3735d5a9ca1f9ad568da4c9a7f17e033c48a7eb4194f
- filename: .gitlab/certs/gitlab-aws.dee.gdit.nat.crt
  checksum: b86064d7494dac173fe8b5c8b1ce7d9df8cde1b11d72060af404a311360291cb
- filename: deploy/deploy-feature/postgres.yaml
  checksum: 00c08e7f284e1ab1eed3a7dbd09de90f16d8dc0fb9a4a46827ced0a0306b360b
- filename: deploy/deploy-main/postgres-deployment.yaml
  checksum: 87b60dc87e0beecb7786a75c6193b06115d34f8abff27a0484226f78e65b6a6c
- filename: .gitlab-ci.yml
  checksum: e449ccf6097fba681e8f3a9ae0060e43cf7d42b4620af6b2ec328194c5af1c8f
- filename: .gitlab-ci.yml
  checksum: af82f4e2e67eef670b39703658f9aa009c35f4f4278d2e33470610226c5af731`

**Comment by umasad087** [comment]
```
custom_severities:
  - detector: ShellHistory
    severity: medium
  - detector: ASCFile
    severity: medium
  - detector: KDBFile
    severity: medium
  - detector: AgileKeyChainFile
    severity: medium
  - detector: PubXML
    severity: medium
  - detector: GitRobRC
    severity: medium
  - detector: ShellRC
    severity: medium
  - detector: CreditCardContent
    severity: medium
  - detector: ShellProfile
    severity: medium
  - detector: ShellAlias
    severity: medium
  - detector: OmniAuth
    severity: medium
  - detector: CarrierWaveRB
    severity: medium
  - detector: SchemaRB
    severity: medium
  - detector: PythonSettings
    severity: medium
  - detector: PhpConfig
    severity: medium
  - detector: PhpLocalSettings
    severity: medium
  - detector: OmniAuth
    severity: medium
  - detector: EnvFile
    severity: medium
  - detector: BDumpFile
    severity: medium
  - detector: BSQLFile
    severity: medium
  - detector: PasswordFile
    severity: medium
  - detector: BackupFile
    severity: medium
  - detector: LogFile
    severity: medium
  - detector: KWallet
    severity: medium
  - detector: GNUCash
    severity: medium
  - detector: PasswordPhrasePattern
    severity: medium
  - detector: LargeFileSize
    severity: medium
fileignoreconfig:
- filename: .gitlab/certs/harbor.app.gdit-dsop.io.crt
  checksum: b8f9ca166189b507a45f3735d5a9ca1f9ad568da4c9a7f17e033c48a7eb4194f
- filename: .gitlab/certs/gitlab-aws.dee.gdit.nat.crt
  checksum: b86064d7494dac173fe8b5c8b1ce7d9df8cde1b11d72060af404a311360291cb
- filename: deploy/deploy-feature/postgres.yaml
  checksum: 00c08e7f284e1ab1eed3a7dbd09de90f16d8dc0fb9a4a46827ced0a0306b360b
- filename: deploy/deploy-main/postgres-deployment.yaml
  checksum: 87b60dc87e0beecb7786a75c6193b06115d34f8abff27a0484226f78e65b6a6c
- filename: .gitlab-ci.yml
  checksum: e449ccf6097fba681e8f3a9ae0060e43cf7d42b4620af6b2ec328194c5af1c8f
- filename: .gitlab-ci.yml
  checksum: af82f4e2e67eef670b39703658f9aa009c35f4f4278d2e33470610226c5af731
```
