### ISSUE TITLE
Need option to Mark false positives in the scan mode

### ISSUE THREAD

**Issue by rmkanda** [thoughtworks/talisman#338]
**Option to Mark false positives in the scan mode**

When scanning the whole git tree, we should have option to mark false positives.  it should be at the commit level, there can be changes the actual secret introduced in the newer commits. 

**Solution:**
In the `.talismanrc` we can add an option to ignore files in a commit and while scanning we can exclude the file from identifying issues.

```
scanignoreconfig:
- commit: b1af11c016038dd47df4cdcd676f919fabacab5e
  filename: danger.pem
  reason: "This is just a test file not an actual key"
```

*Workflow*
1) Scanning a Repo - CI

  - Developer add talisman in the CI
  - Talisman produces list of issues
  - Developer reviews the issues and updates the ignore rc file
  - Makes a new commit 
  - Runs the scan again, there should not be any issues shown

2) Developer making New commit with a false positive issue

  - Developer installs talisman in local machine with commit hook option
  - Developer makes a commit
  - Talisman produces list of issues
  - Developer reviews the issues and updates the ignore rc file - fileignoreconfig section 
  - Makes a the commit 
  - Once the commit succeeds. Developer has to add a commit by including this in the  scanignoreconfig section of RC.
  - Pushes the code changes
  - Talisman runs in the CI and honours the rc file.
