### ISSUE TITLE
Suggested checksum is incorrect when there are multiple files with the same name

### ISSUE THREAD

**Issue by wf-anniezhou** [thoughtworks/talisman#344]
**Describe the bug**
When Talisman finds an error in a file at the root level, and there is another file with the **exact same name** in a different folder, the suggest checksum to paste into `.talismanrc` will **not**  cause the errors to be ignored when running Talisman again.

**To Reproduce**
1. Create a repo that contains a `child` folder, create an empty file under that folder (e.g. `README.md`)
2. Make a commit
2. Create a file with the same name (e.g. `README.md`) at the root level. Include a sensitive pattern in this file. 
2. Run the Talisman pre-commit hook, it will report an error related to the sensitive pattern and output the following: 
  ```
  If you are absolutely sure that you want to ignore the above files from talisman detectors, consider pasting the following format in .talismanrc file in the project root
  
  fileignoreconfig:
  - filename: README.md
    checksum: <someChecksumString>
  
  ```
5. Paste the suggested `fileignoreconfig` into `.talismanrc`
6. Run the Talisman pre-commit hook again, it will report the same error and suggest the same `fileignoreconfig` even though you have already added this in `.talismanrc`

**Expected behavior**
Pasting the suggested `fileignoreconfig` into `.talismanrc` should cause the errors to be ignored.

**Likely cause**
The checksum suggested by Talisman is for the **individual file** containing the sensitive pattern. When checking for whether a file should be ignored, the file name in `.talismanrc` is treated as a pattern and matched to both `README.md` and `child/README.md`.

If you run `talisman --checksum README.md`, it will output a **different checksum string** to the one generated above. Putting this different checksum into `.talismanrc` will cause the error to be ignored, which is the correct behavior. This indicates there's a mismatch relating to the checksum being generated.
