### ISSUE TITLE
Running into CI

### ISSUE THREAD

**Issue by darakeon** [thoughtworks/talisman#348]
## **Is your feature request related to a problem? Please describe.**
I'm trying to run talisman at a CI.

## **Describe the solution you'd like**
A documentation of how to install talisman without interaction.

## **Describe alternatives you've considered**
No alternatives, I'm trying to use the recommended installation.

## **Additional context**
I'm trying to build a dockerfile for this. The code I've built until now (my machine is based in an official ubuntu docker):

```dockerfile
RUN apt install -y libdigest-sha-perl
RUN apt install -y git

RUN curl --silent  https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/install.bash > /tmp/install_talisman.bash
RUN chmod +x /tmp/install_talisman.bash

ENV TALISMAN_HOME=~/.bashrc

RUN /bin/bash /tmp/install_talisman.bash
```

My problem is at line 189. `read` results this:
```
/tmp/install_talisman.bash: line 189: read: read error: 1: Bad file descriptor
```

**Comment by tinamthomas** [comment]
@darakeon  


1. The error you're seeing on line 189 is because the install script is prompting for setting up the Git template directory. This can be set through the git config command:

```
RUN git config --global init.templatedir /home/.git-template
```
2. The talisman install will also prompt you to provide a root directory to search for git repos. Currently we don't have a way to externally provide this via environment variable. An alternative solution would be to pipe to the install command

```
RUN echo "/root" | /bin/bash /tmp/install_talisman.bash
``` 
3. TALISMAN_HOME should be a directory

Adding the following changes to your dockerfile should unblock you
```
ENV TALISMAN_HOME=/home
RUN git config --global init.templatedir /home/.git-template
RUN echo "/root" | /bin/bash /tmp/install_talisman.bash
```

**Comment by tinamthomas** [comment]
Also just saw the pull request you raised. Thank! Will take a look at it.

**Comment by darakeon** [comment]
Talisman image created:
https://github.com/darakeon/server/blob/main/docker/images/talisman.dockerfile

Locally it is working, but... yeah, using docker, and still having "but works at my machine" trying to use the docker inside circleCI now. Just out of curiosity, this is the repo I'm using to test:
https://github.com/darakeon/meak/blob/talisman/.circleci/config.yml#L4

Thanks a lot! Specially for the tip of using `|` to "answer" the script, I didn't know this one. Using `\n` I could put all the answers inside same `echo`.

**Comment by darakeon** [comment]
I will close the issue now, because I was able to run talisman into CI! Nice!

But I will wait to ignore to be implemented into `--scan`, talisman is detecting pieces of characters inside images as dangerous secrets.

In case someone comes here and the above links do not work anymore, here is dockerfile steps:

```dockerfile
RUN apt install -y libdigest-sha-perl

RUN apt install -y git
RUN git config --global init.templatedir /home/.git-template

RUN curl --silent https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/install.bash > /tmp/install_talisman.bash
RUN chmod +x /tmp/install_talisman.bash

# to avoid problem with tput 
ENV TERM=dumb
RUN echo "1\n\n/root" | /bin/bash /tmp/install_talisman.bash
```

and circleCI config:

```yaml
version: 2.1

jobs:
  talisman:
    docker:
      - image: # your image goes here, or you can use mine: darakeon/talisman
    resource_class: small
    environment:
      TALISMAN_HOME: /root/.talisman/bin
      TALISMAN_INTERACTIVE: false
    steps:
      - checkout
      - run:
          name: Check Talisman
          command: $TALISMAN_HOME/talisman_linux_amd64 --scan # I've added --ignoreHistory to the end here
      - store_artifacts:
          path: talisman_report/talisman_reports/data
          destination: talisman_report
```
