### ISSUE TITLE
integrate Talisman into the pre-commit framework

### ISSUE THREAD

**Issue by CiSpiker** [thoughtworks/talisman#36]
Talisman is a great basic tool, but it doesn't play nicely with other frameworks, and as mentioned in #35 and #26 there is interest in using it standalone, or with other tools.

The pre-commit framework (https://github.com/pre-commit/pre-commit) is an open-source framework for defining and combining multiple pre-commit hooks for a project.  It would be extremely convenient to be able to use talisman within this framework - and it could also simplify talisman by allowing pre-commit to take care of the git integration side of things.

**Comment by kornysietsma** [comment]
Oops - I created this with a temporary github user I happened to be logged in to!  Sorry, this should have been added by me (Korny Sietsma)

**Comment by asottile** [comment]
pre-commit maintainer here :)

I can help getting started with a configuration that mostly works today (and could be adjusted in the future if more of the `git` responsibilities want to be pushed off to `pre-commit` itself)

### `.pre-commit-manifest.yaml`
```yaml
-   id: talisman-commit
    name: talisman
    entry: talisman -githook pre-commit
    stages: [commit]
    # talisman currently discovers files by itself and does not take them on the cli
    pass_filenames: false
    types: [text]
    language: golang

-   id: talisman-push
    name: talisman
    entry: talisman -githook pre-push
    stages: [push]
    # talisman currently discovers files by itself and does not take them on the cli
    pass_filenames: false
    types: [text]
    language: golang
```
