### ISSUE TITLE
docs: introducing homebrew installation 

### ISSUE THREAD

**Issue by jjangga0214** [thoughtworks/talisman#410]
Hi!
Would you introduce an installation process with homebrew/linuxbrew on docs?
I think it'd be helpful to many people.
Thanks :)

**Comment by tinamthomas** [comment]
This would be a good first issue, to update the readme with homebrew installation instructions.

https://github.com/thoughtworks/talisman/issues/51

**Comment by exageraldo** [comment]
In my team we have some people who have installed Talisman as a global template and others who have installed it via homebrew.


We're using pre-commit and the configuration that worked for us in both cases was:

https://github.com/thoughtworks/talisman#1-pre-commit-linuxunix
```
-   repo: local
    hooks:
    -   id: talisman-precommit
        name: talisman
        entry: bash -c 'if [! talisman --version &> /dev/null];then talisman --githook pre-commit; elif [ -n "${TALISMAN_HOME:-}" ]; then ${TALISMAN_HOME}/talisman_hook_script pre-commit; else echo "TALISMAN does not exist. Consider installing from https://github.com/thoughtworks/talisman . If you already have talisman installed, please ensure TALISMAN_HOME variable is set to where talisman_hook_script resides, for example, TALISMAN_HOME=${HOME}/.talisman/bin"; fi'
        language: system
        pass_filenames: false
        types: [text]
        verbose: true
```
