### ISSUE TITLE
Even after adding the checksum talisman is still throwing error which is so annoying

### ISSUE THREAD

**Issue by mai1x9** [thoughtworks/talisman#463]
**Describe the bug**
- Talisman showed to add the checksum 
```
fileignoreconfig:
- filename: .env
  checksum: 908d465d343b767253e77c80d7f12c592aa7fdab854b0d1f6a0b6999c5528321
version: ""
```

- Rerun the tailsman, it shows the same erorr and same checksum. This is so frustrating. Even if checksum is not changed why the hell it is showing the error report again and again. The entire pre commit is failing because of this non sense issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04

**Smartphone (please complete the following information):**

**Additional context**
Talisman version: v1.28.0

Git pre-commit-conf.yml
```
  - repo: https://github.com/thoughtworks/talisman
    rev: "v1.28.0"
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit

```

**Comment by harinee** [comment]
Hi, 
So you copied the same filename and checksum to your talismanrc and it still doesn't ignore this?
Could you please also double-check if all the syntax look right in the talismanrc file? 
If you can, please share your talismanrc file?

**Comment by mai1x9** [comment]
> Hi, So you copied the same filename and checksum to your talismanrc and it still doesn't ignore this? Could you please also double-check if all the syntax look right in the talismanrc file? If you can, please share your talismanrc file?

Hi thank you for reply. Right it doesn't change. everytime I run commit, pre hook executes and talisman gives same check sum. 

I have added fileignore as shown in issue. I don't know why it ist working. Only when checksum changes it will show the error again. But the checksum is same.....


I tried to add ignore detectors too and ignored the file content for now to bypass this and it worked. I could fix it but no wonder why it didn't work at first place.

**Comment by seifrajhi** [comment]
+1
facing the exact same issue

**Comment by deepthirera** [comment]
Hi @mai1x9 
Could you please give us more details on this?
1. Is this happening with any file or just with .env file? We tried reproducing the issue but it doesn't happen. 
2. Provide us more details on '...' mentioned in the steps to reproduce. 
3. Share your .talismanrc file if possible.
4. Is there another .env file(file with the name .env) in any of the subfolders?

**Comment by mai1x9** [comment]
> Hi @mai1x9 Could you please give us more details on this?
> 
> 1. Is this happening with any file or just with .env file? We tried reproducing the issue but it doesn't happen.
> 2. Provide us more details on '...' mentioned in the steps to reproduce.
> 3. Share your .talismanrc file if possible.
> 4. Is there another .env file(file with the name .env) in any of the subfolders?

Hi @deepthirera 

I think the Issue has occured again. Its occuring with `.env` as well as `package-lock.json` files only. Even if they are added in `.talismanrc` still its showing the error.

The `.talismanrc` file 

```
fileignoreconfig:
- filename: config/.env
  checksum: 537ca087a26360147e71d80b62b24a044e35ca5411e0ca87bb86043ffba8c148
- filename: package-lock.json
  checksum: 7f195ce0ae38cca4e11270502a5842bbc4e2e74feb16d804a9ffe57cbbab8834
- filename: tools/check_absurd_versions.js
  checksum: 229653fc59a1ab19cab29201f25198bdf5c011b835edf8fa11cc140ed4e6837c
- filename: helpers/cvss.js
  checksum: 4e61d19e32e551784f2ac89aaea76dd4ed2da64a53704af920ae448c6242e705
- filename: config/.env
  checksum: 6ac12a3f0f7451e1f30bcaea3706493beaeb0c5276f0f06e6a4454cd3a2f0db7
- filename: package-lock.json
  checksum: 83d9db6db2714a3f8e975226df0fe7d7f2a5d82cf09ceecc775f83983ed7113a
version: ""

```
As you can see from below screenshot, the hash values are correct for `.env` and `package-lock.json`, still its not working.

<img width="821" alt="image" src="https://github.com/user-attachments/assets/35f9041b-1516-43e5-b88c-095547e167f7">

**Comment by deepthirera** [comment]
Hi @mai1x9,
Thanks for sharing the details of the issue.
Are there multiple .env or package-lock.json files in your project directory? If so, then this might be related to [#416 ](https://github.com/thoughtworks/talisman/issues/416)

**Comment by mai1x9** [comment]
@deepthirera 
Yeah you are right. The project has multiple env files, one for dev. test and prod.

Also we use lot of git sub modules, so yeah we may end up woth multiple package locks.

will check your suggestion and try. Thank you

**Comment by carterbox** [comment]
```
fileignoreconfig:
- filename: config/.env
  checksum: 537ca087a26360147e71d80b62b24a044e35ca5411e0ca87bb86043ffba8c148
- filename: package-lock.json
  checksum: 7f195ce0ae38cca4e11270502a5842bbc4e2e74feb16d804a9ffe57cbbab8834
- filename: tools/check_absurd_versions.js
  checksum: 229653fc59a1ab19cab29201f25198bdf5c011b835edf8fa11cc140ed4e6837c
- filename: helpers/cvss.js
  checksum: 4e61d19e32e551784f2ac89aaea76dd4ed2da64a53704af920ae448c6242e705
- filename: config/.env
  checksum: 6ac12a3f0f7451e1f30bcaea3706493beaeb0c5276f0f06e6a4454cd3a2f0db7
- filename: package-lock.json
  checksum: 83d9db6db2714a3f8e975226df0fe7d7f2a5d82cf09ceecc775f83983ed7113a
version: ""
```

The filenames in [the provided config](https://github.com/thoughtworks/talisman/issues/463#issuecomment-2442308967) are non-unique. `config/.env` is listed twice. I would assume that this is not allowed and talisman might be using the first checksum it finds.
